---
- name: Deploy IPFS, Subtensor, and Hippius nodes
  hosts: ipfs_nodes
  become: yes

  roles:
    - common
    #- { role: docker, when: skip_docker is not defined or not skip_docker }
    - ipfs
    - { role: subtensor, when: skip_subtensor is not defined or not skip_subtensor }
    - hippius
